import AppKit

/// The character, loaded as data rather than reimplemented.
///
/// Every frame Wity can be in is generated by the Python module and baked into
/// the bundle at build time. Drawing code here, art there: one source of truth,
/// for the same reason the page's headline is derived from the mood rather than
/// ranked a second time.
public struct Mascot: Decodable {
    /// One character in the cast. Everything that makes it *that* character
    /// lives in the art; this is only what a picker needs to name it.
    public struct Figure: Decodable, Identifiable, Hashable {
        public let id: String
        public let name: String
        /// Which part of it always takes the status colour. A figure whose
        /// eyes are dark would otherwise lose the tint entirely at 22 pixels
        /// and stop being an instrument — so every one declares a tell, and
        /// the picker says what it is.
        public let tell: String
    }

    public let width: Int
    public let height: Int
    public let frames: Int
    public let slots: [String: String]
    public let skins: [String: [String: String]]
    public let defaultSkin: String
    public let sprites: [String: [String]]
    public let walkSprites: [String: [String]]?
    public let figures: [Figure]
    public struct Companion: Decodable {
        public let width: Int
        public let height: Int
        public let sprites: [String: [String]]
        public let walkingSprites: [String: [String]]?
        public let palettes: [String: [String: String]]
    }
    public let companion: Companion?
    public let menu: Companion?
    public let defaultFigure: String

    public enum CodingKeys: String, CodingKey {
        case width, height, frames, slots, skins, sprites, figures, companion, menu
        case walkSprites = "walk_sprites"
        case defaultSkin = "default_skin"
        case defaultFigure = "default_figure"
    }

    public static func load(_ url: URL) -> Mascot? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(Mascot.self, from: data)
    }

    /// Falls back to the default figure, because a saved preference outlives
    /// the character it names: a cast member renamed between releases would
    /// otherwise leave the app with no face and no explanation.
    ///
    /// The fallback is on the whole key, not on the figure id. Testing
    /// `sprites[figure]` looks right and is always nil — the dictionary is
    /// keyed by the composed `figure/gauge/eyes/frame`, so every figure took
    /// the fallback and the entire cast rendered as the cat.
    public func rows(figure: String, gauge: Int, eyes: String, frame: Int) -> [String]? {
        let f = frame % max(frames, 1)
        return sprites["\(figure)/\(gauge)/\(eyes)/\(f)"]
            ?? sprites["\(defaultFigure)/\(gauge)/\(eyes)/\(f)"]
    }

    public func has(figure: String) -> Bool {
        figures.contains { $0.id == figure }
    }
}

public enum Ink {
    /// `#rrggbb` as written by the Python palette. Anything unparseable returns
    /// nil so a bad colour shows as a hole rather than silently as black — a
    /// missing pixel is noticed, a black one is not.
    public static func color(_ hex: String) -> NSColor? {
        var s = hex
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6, let v = UInt32(s, radix: 16) else { return nil }
        return NSColor(srgbRed: CGFloat((v >> 16) & 0xff) / 255,
                       green: CGFloat((v >> 8) & 0xff) / 255,
                       blue: CGFloat(v & 0xff) / 255, alpha: 1)
    }
}

extension Mascot {
    /// One frame as an image, sized to fit `height` points.
    ///
    /// Drawn at an integral pixel scale and never interpolated: a pixel
    /// character resampled to a fractional size stops being pixel art and
    /// becomes a smudge, which is exactly what it looks like when it goes wrong.
    public func image(figure: String, gauge: Int, eyes: String, frame: Int, skin: String,
               tint: String, fitting height: CGFloat, mood: String? = nil, detailed: Bool = false,
               showSignal: Bool = true, walking: Bool = false, facesLeft: Bool = false) -> NSImage? {
        let dedicatedArt = detailed ? companion : (!showSignal ? menu : nil)
        if let art = dedicatedArt,
           let rows = (walking
                ? art.walkingSprites?["\(figure)/\(eyes)/\(frame % max(frames, 1))"]
                : nil) ?? art.sprites["\(figure)/\(eyes)/\(frame % max(frames, 1))"],
           let palette = art.palettes["\(figure)/\(skin)"] ?? art.palettes["\(figure)/\(defaultSkin)"] {
            // Detailed art fits in full. Never crop or fractionally resample it.
            let scale = max(1, floor(height / CGFloat(art.height)))
            let size = NSSize(width: CGFloat(art.width) * scale, height: CGFloat(art.height) * scale)
            let image = NSImage(size: size)
            image.lockFocus()
            NSGraphicsContext.current?.imageInterpolation = .none
            let context = NSGraphicsContext.current?.cgContext
            context?.saveGState()
            if facesLeft {
                context?.translateBy(x: size.width, y: 0)
                context?.scaleBy(x: -1, y: 1)
            }
            for (y, row) in rows.enumerated() {
                for (x, ch) in row.enumerated() where ch != "." {
                    guard let color = Ink.color(palette[String(ch)] ?? "") else { continue }
                    color.setFill()
                    NSRect(x: CGFloat(x)*scale, y: CGFloat(art.height-1-y)*scale,
                           width: scale, height: scale).fill()
                }
            }
            context?.restoreGState()
            if let mood, showSignal {
                // Keep the badge at menu-bar size so art stays the focus.
                MascotSignal.draw(mood: mood, tint: tint, at: NSPoint(x: size.width-9, y: 0), scale: 1)
            }
            image.unlockFocus()
            return image
        }
        let walkingRows = walking
            ? (companion?.walkingSprites?["\(figure)/\(eyes)/\(frame % max(frames, 1))"]
                ?? walkSprites?["\(figure)/\(gauge)/\(eyes)/\(frame % max(frames, 1))"])
            : nil
        guard let rows = walkingRows ?? rows(figure: figure, gauge: gauge, eyes: eyes, frame: frame)
        else { return nil }
        let palette = skins[skin] ?? skins[defaultSkin] ?? [:]
        let accent = Ink.color(tint) ?? .systemGreen

        // Integral scale, then crop to fit rather than shrink to fit. The menu
        // bar is 22pt and the character is 23 rows, so "scale to fit" would
        // resample by 22/23 and turn pixel art into a smudge. Losing the bottom
        // row of outline is invisible; a fractional scale is not.
        let scale = max(1, floor(height / CGFloat(self.height)))
        let maxRows = max(1, Int(floor(height / scale)))
        let drawnRows = min(self.height, maxRows)
        let size = NSSize(width: CGFloat(width) * scale, height: CGFloat(drawnRows) * scale)
        let image = NSImage(size: size)
        image.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .none
        let context = NSGraphicsContext.current?.cgContext
        context?.saveGState()
        if facesLeft {
            context?.translateBy(x: size.width, y: 0)
            context?.scaleBy(x: -1, y: 1)
        }
        for (y, row) in rows.enumerated() where y < drawnRows {
            for (x, ch) in row.enumerated() where ch != "." {
                guard let slot = slots[String(ch)] else { continue }
                let color = slot == "accent" ? (mood == nil ? accent : Ink.color(palette["pale"] ?? "")) : Ink.color(palette[slot] ?? "")
                guard let color else { continue }
                color.setFill()
                // Sprite rows run top-down; AppKit's origin is bottom-left.
                NSRect(x: CGFloat(x) * scale,
                       y: CGFloat(drawnRows - 1 - y) * scale,
                       width: scale, height: scale).fill()
            }
        }
        context?.restoreGState()
        if let mood, showSignal {
            MascotSignal.draw(mood: mood, tint: tint, at: NSPoint(x: size.width - 9, y: 0), scale: 1)
        }
        image.unlockFocus()
        return image
    }
}
