import XCTest
@testable import WTManagerKit

/// The renderer, tested where being wrong is silent.
///
/// Every failure here previously showed up as "the menu bar item is missing" or
/// "the character looks like a smudge" — symptoms a long way from their cause.
final class MascotTests: XCTestCase {

    private func load() throws -> Mascot {
        // The art is generated by the Python module, so the test reads whatever
        // the build would bundle rather than a fixture that can drift from it.
        let here = URL(fileURLWithPath: #filePath)
        let engine = here.deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().deletingLastPathComponent()
        let json = engine.appendingPathComponent("mascot.json")
        // Regenerated every run, not only when absent. A file left over from
        // an earlier shape of the art decodes as whatever it was — and when
        // the cast was added, every test here failed against a copy written
        // before the cast existed, which reads as "the renderer is broken"
        // rather than as "the fixture is stale".
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        p.arguments = [engine.appendingPathComponent("mascot.py").path, json.path]
        p.standardOutput = FileHandle.nullDevice
        try p.run(); p.waitUntilExit()
        return try XCTUnwrap(Mascot.load(json), "could not load the character")
    }

    func testEverySpriteIsTheDeclaredSize() throws {
        let m = try load()
        for (key, rows) in m.sprites {
            XCTAssertEqual(rows.count, m.height, "\(key) height")
            for row in rows {
                XCTAssertEqual(row.count, m.width, "\(key) width")
            }
        }
    }

    func testEveryFigureHasEveryGaugeAndExpression() throws {
        let m = try load()
        XCTAssertFalse(m.figures.isEmpty, "no cast at all")
        for figure in m.figures {
            for gauge in 0..<4 {
                for eyes in ["open", "shut", "wide", "squint", "glance"] {
                    for frame in 0..<m.frames {
                        XCTAssertNotNil(
                            m.rows(figure: figure.id, gauge: gauge, eyes: eyes, frame: frame),
                            "missing \(figure.id)/\(gauge)/\(eyes)/\(frame)")
                    }
                }
            }
        }
    }

    func testAFigureNobodyShipsFallsBackRatherThanVanishing() throws {
        // A saved preference outlives the character it names — a cast member
        // renamed or dropped between releases would otherwise leave the app
        // with no face and no explanation.
        let m = try load()
        XCTAssertNotNil(m.rows(figure: "no-such-animal", gauge: 0, eyes: "open", frame: 0))
        XCTAssertEqual(m.rows(figure: "no-such-animal", gauge: 0, eyes: "open", frame: 0),
                       m.rows(figure: m.defaultFigure, gauge: 0, eyes: "open", frame: 0))
        XCTAssertTrue(m.has(figure: m.defaultFigure))
        XCTAssertFalse(m.has(figure: "no-such-animal"))
    }

    func testTheDefaultFigureIsUnchangedByTheCast() throws {
        // Wity is the figure people have been looking at, and the refactor
        // that made a figure into data shifted every one of them up a pixel
        // for a bob only the tailless ones need — which drove his ears into
        // his own tail. A shared origin is not a place to put one figure's
        // animation. These are the rows of the art as it was.
        let m = try load()
        let rows = try XCTUnwrap(m.rows(figure: "cat", gauge: 0, eyes: "open", frame: 0))
        XCTAssertEqual(rows.first, "..........##..........", "the plume moved")
        XCTAssertEqual(rows[7], ".....##.....#ss##ss#..", "an ear is in the tail")
        // Anchored on the origin, not on the feet: the feet are art and the
        // art may change. That he stands on the bottom row is the thing the
        // shared offset broke.
        XCTAssertNotEqual(rows.last?.trimmingCharacters(in: CharacterSet(charactersIn: ".")), "",
                          "he is floating above the floor")
    }

    func testEveryFigureIsTellablyDifferentFromEveryOther() throws {
        // Four characters that render identically are one character and three
        // wasted picker entries.
        let m = try load()
        var seen: [String: String] = [:]
        for f in m.figures {
            let art = (m.rows(figure: f.id, gauge: 2, eyes: "open", frame: 0) ?? []).joined()
            if let twin = seen[art] { XCTFail("\(f.id) draws the same as \(twin)") }
            seen[art] = f.id
            XCTAssertFalse(f.tell.isEmpty, "\(f.id) declares no tell")
        }
    }

    func testEveryFigureCarriesTheStatusColourSomewhere() throws {
        // The whole point of the tell: a figure whose eyes are dark loses the
        // tint entirely at 22 pixels and stops being an instrument.
        let m = try load()
        let accent = m.slots.first { $0.value == "accent" }?.key
        let mark = try XCTUnwrap(accent).first
        for f in m.figures {
            for eyes in ["open", "shut", "wide"] {
                let art = (m.rows(figure: f.id, gauge: 0, eyes: eyes, frame: 0) ?? []).joined()
                XCTAssertTrue(art.contains(try XCTUnwrap(mark)),
                              "\(f.id) has no accent pixel with \(eyes) eyes")
            }
        }
    }

    func testEveryCharacterRendersTheSameSignalAtActualMenuBarSize() throws {
        let m = try load()
        for mood in MascotSignal.moods {
            var reference: [String]?
            for figure in m.figures {
              for skin in m.skins.keys {
                let image = try XCTUnwrap(m.image(figure: figure.id, gauge: 0, eyes: "open", frame: 0,
                    skin: skin, tint: MascotSignal.colors[mood]!, fitting: 22, mood: mood))
                XCTAssertEqual(image.size, NSSize(width: 22, height: 22))
                let pixels = try XCTUnwrap(NSBitmapImageRep(data: try XCTUnwrap(image.tiffRepresentation)))
                let sx = pixels.pixelsWide / 22, sy = pixels.pixelsHigh / 22
                var badge: [String] = []
                for y in 13..<22 { for x in 13..<22 {
                    let c = try XCTUnwrap(pixels.colorAt(x: x*sx, y: y*sy)?.usingColorSpace(.deviceRGB))
                    badge.append(String(format: "%.3f/%.3f/%.3f/%.3f", c.redComponent,c.greenComponent,c.blueComponent,c.alphaComponent))
                } }
                if let reference { XCTAssertEqual(badge, reference, "\(figure.id)/\(mood) signal changed") }
                else { reference = badge }
              }
            }
        }
    }

    func testDetailedCompanionsFitFullyAndMenuBarStaysSmall() throws {
        let m = try load()
        for figure in ["robot", "rooster", "rabbit", "snowman", "palm"] {
            let large = try XCTUnwrap(m.image(figure: figure, gauge: 3, eyes: "wide", frame: 7,
                skin: "chestnut", tint: "#e0604c", fitting: 69, mood: "alarmed", detailed: true))
            XCTAssertEqual(large.size, NSSize(width: 64, height: 64))
            let small = try XCTUnwrap(m.image(figure: figure, gauge: 3, eyes: "wide", frame: 7,
                skin: "chestnut", tint: "#e0604c", fitting: 22, mood: "alarmed"))
            XCTAssertEqual(small.size, NSSize(width: 22, height: 22))
        }
    }

    func testOlderDataAndExistingCharactersKeepFallbackArtwork() throws {
        let m = try load()
        let encoderData = try Data(contentsOf: URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent("mascot.json"))
        var object = try XCTUnwrap(JSONSerialization.jsonObject(with: encoderData) as? [String: Any])
        object.removeValue(forKey: "companion")
        let old = try JSONDecoder().decode(Mascot.self, from: JSONSerialization.data(withJSONObject: object))
        for figure in ["robot", "cat", "crab", "missing"] {
            XCTAssertNotNil(old.image(figure: figure, gauge: 0, eyes: "open", frame: 0,
                skin: "acorn", tint: "#3fb27f", fitting: 69, detailed: true))
        }
        XCTAssertNotNil(m.image(figure: "cat", gauge: 0, eyes: "open", frame: 0,
            skin: "acorn", tint: "#3fb27f", fitting: 69, detailed: true))
    }

    func testFramesWrapRatherThanFallingOff() throws {
        let m = try load()
        XCTAssertEqual(m.rows(figure: m.defaultFigure, gauge: 0, eyes: "open", frame: m.frames + 1),
                       m.rows(figure: m.defaultFigure, gauge: 0, eyes: "open", frame: 1))
    }

    func testTheGaugeActuallyChangesTheArt() throws {
        let m = try load()
        // If the pouches did not differ between levels the gauge would be
        // decoration, which is the one thing it must not be.
        XCTAssertNotEqual(m.rows(figure: m.defaultFigure, gauge: 0, eyes: "open", frame: 0),
                          m.rows(figure: m.defaultFigure, gauge: 3, eyes: "open", frame: 0))
    }

    func testTheTailMovesBetweenFrames() throws {
        let m = try load()
        XCTAssertNotEqual(m.rows(figure: m.defaultFigure, gauge: 1, eyes: "open", frame: 0),
                          m.rows(figure: m.defaultFigure, gauge: 1, eyes: "open", frame: 1))
    }

    func testEverySlotUsedByTheArtHasAName() throws {
        let m = try load()
        var used = Set<Character>()
        for rows in m.sprites.values {
            for row in rows { used.formUnion(row) }
        }
        used.remove(".")
        for ch in used {
            XCTAssertNotNil(m.slots[String(ch)], "slot '\(ch)' has no name")
        }
    }

    func testEverySkinPaintsEverySlotExceptTheLiveOne() throws {
        let m = try load()
        // accent is deliberately absent: it is the status tint, resolved per
        // frame, and a skin that defined it would silently outrank the status.
        let needed = Set(m.slots.values).subtracting(["accent"])
        for (name, skin) in m.skins {
            XCTAssertTrue(needed.isSubset(of: Set(skin.keys)),
                          "\(name) is missing \(needed.subtracting(Set(skin.keys)))")
            XCTAssertNil(skin["accent"], "\(name) defines accent, which is the status tint")
        }
    }

    func testColoursParse() {
        XCTAssertNotNil(Ink.color("#1a1614"))
        XCTAssertNotNil(Ink.color("1a1614"))
        XCTAssertNil(Ink.color("#xyz"))
        XCTAssertNil(Ink.color(""))
    }

    func testTheMenuBarImageIsCroppedRatherThanSquashed() throws {
        let m = try load()
        // 22pt of bar for 23 rows: scaling to fit resamples pixel art into a
        // smudge, so it must take whole pixels and lose the last row instead.
        let image = try XCTUnwrap(m.image(figure: m.defaultFigure, gauge: 2, eyes: "open", frame: 0,
                                          skin: m.defaultSkin, tint: "#3fb27f",
                                          fitting: 22))
        XCTAssertEqual(image.size.height, 22, "height should fill the bar exactly")
        XCTAssertEqual(image.size.width, CGFloat(m.width), "width should be 1pt per pixel")
    }

    func testALargerFitScalesByWholePixels() throws {
        let m = try load()
        let image = try XCTUnwrap(m.image(figure: m.defaultFigure, gauge: 0, eyes: "open", frame: 0,
                                          skin: m.defaultSkin, tint: "#3fb27f",
                                          fitting: 70))
        // 70 / 23 -> 3x, so 69 tall and 3x wide. Never a fractional scale.
        XCTAssertEqual(image.size.height, 69)
        XCTAssertEqual(image.size.width, CGFloat(m.width) * 3)
    }

    func testAnUnknownSkinFallsBackRatherThanFailing() throws {
        let m = try load()
        XCTAssertNotNil(m.image(figure: m.defaultFigure, gauge: 0, eyes: "open", frame: 0,
                                skin: "no-such-skin", tint: "#3fb27f", fitting: 44))
    }
}
